# Site settings
title: CamGW
description: The Cambridge Gravitational-Wave Network

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

# Navigation
header_pages:
  - index.md
  - meetings.md
  - students.md
  - people.md
  - research.md
  - news.md
  - publications.md
